// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/weather.ts";
import * as $4 from "./routes/count.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/weather.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/NavBar.tsx";
import * as $$2 from "./islands/Searcher.tsx";
import * as $$3 from "./islands/WeatherSearch.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/weather.ts": $3,
    "./routes/count.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/weather.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/NavBar.tsx": $$1,
    "./islands/Searcher.tsx": $$2,
    "./islands/WeatherSearch.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
